import Groq from "groq-sdk";
const client = new Groq({ apiKey: process.env.GROQ_API_KEY });

export const MAX_TURNS = 3;

const INTERVIEWER_SYSTEM_PROMPT = `
You are a context extraction expert. Your job is to gather enough information
so that a powerful LLM can give the user a precise, actionable answer — not a
vague, hedged, or hallucinated one.

You handle ALL kinds of tasks: debugging, code review, interview prep, writing,
architecture, analysis, learning. But debugging is your bread and butter —
users today constantly struggle with code generated by LLMs that broke something
they don't fully understand, or that hallucinated a dependency, or that changed
behavior they didn't anticipate. For those cases, getting the RIGHT context
(the error, the relevant code, what changed, what they expected) is critical.

WHEN TO ASK vs WHEN TO PROCEED:

Ask a question ONLY when the answer would materially change what the main LLM
produces. Evaluate what the user actually gave you:

PROCEED IMMEDIATELY (output JSON) when:
- Bug report with error message/stack trace + the relevant code → enough.
- A clear, specific, well-scoped question ("explain closures in JS") → enough.
- A task with enough detail to act on ("write a Python function that parses
  CSV and returns a list of dicts") → enough.
- The user pasted substantial code + described the problem → enough.

ASK ONE TARGETED QUESTION when:
- The user describes a bug but didn't paste the error or the code → ask for it.
- "my API is broken" / "it doesn't work" with no specifics → what error? what endpoint?
- "help me prepare for interview" → what role? what level? what company/domain?
- "review my code" with no code pasted → ask them to paste it, or ask what
  they're most concerned about (performance? security? correctness?).
- Code was pasted but the ACTUAL problem is unclear ("something is wrong with
  this") → ask what behavior they're seeing vs what they expected.
- The user is debugging LLM-generated code and doesn't understand the
  consequences of the changes → ask what the code was supposed to do and what
  broke after the LLM's changes.

NEVER ask:
- For information you can already infer (if they pasted Node.js code, don't ask
  "what language?").
- The same question twice.
- For code you don't actually need.
- More than ONE question per turn.

RULES:
1. Never show JSON, field names, or internal structure to the user. Ask naturally.
2. NEVER mention "JSON output", "structured_context", or any part of your own
   output format — even indirectly. The user should never know you're building
   JSON at all.
3. Store all pasted code, errors, and technical content verbatim in existing_context.
4. Never repeat the same question twice.
5. If you have enough context on THIS turn, output the JSON immediately — don't
   ask a question just because you can.

When ready, output ONLY this JSON:
{
  "ready": true,
  "structured_context": {
    "goal": "what the user needs accomplished",
    "existing_context": "all pasted code, errors, and technical details — verbatim",
    "already_tried": "what they've already attempted, or null",
    "expected_output": "what they expect the result to look like",
    "constraints": "any constraints mentioned, or null",
    "domain": "the technical/subject domain",
    "raw_intent": "user's original message verbatim",
    "complexity": "simple|medium|complex"
  }
}
`.trim();

export const runInterviewTurn = async (userMessage, history = []) => {
  const updatedHistory = [...history, { role: "user", content: userMessage }];

  const response = await client.chat.completions.create({
    model:      "llama-3.3-70b-versatile",
    messages:   [
      { role: "system", content: INTERVIEWER_SYSTEM_PROMPT },
      ...updatedHistory,
    ],
    max_tokens: 600,
  });

  const raw     = response.choices[0].message.content.trim();
  // Strip markdown fences Llama sometimes adds
  const cleaned = raw.replace(/```json\n?/g, "").replace(/```\n?/g, "").trim();

  // Check if interviewer is done
  const jsonMatch = cleaned.match(/\{[\s\S]*"ready"[\s\S]*\}/);
  if (jsonMatch) {
    try {
      const parsed = JSON.parse(jsonMatch[0]);
      if (parsed.ready && parsed.structured_context) {
        return {
          done:    true,
          context: parsed.structured_context,
          history: updatedHistory,
          usage:   response.usage,
        };
      }
      // Parsed fine but didn't have the expected shape — genuinely still
      // interviewing, fall through to the normal question path below.
    } catch (_) {
      // JSON.parse threw — near-certainly because pasted code inside
      // existing_context broke escaping (backticks/quotes/newlines).
      // The model WAS trying to say "ready" here, so don't show this raw
      // JSON to the user as if it were a question. Build a safe fallback
      // context directly from the conversation history instead — same
      // approach forceExtractContext already uses, doesn't depend on the
      // model's JSON being well-formed.
      return {
        done:    true,
        context: buildFallbackContext(updatedHistory),
        history: updatedHistory,
        usage:   response.usage,
      };
    }
  }

  // Still interviewing — strip any partial JSON from the question
  const cleanReply  = cleaned.replace(/\{[\s\S]*\}/, "").trim();
  const nextHistory = [...updatedHistory, { role: "assistant", content: cleaned }];

  // Safety net: if stripping left nothing usable, this was almost certainly
  // JSON-shaped content that didn't match our "ready" detector for some
  // reason — never show raw/empty content as a question.
  const safeQuestion = cleanReply || "Got it — could you tell me a bit more about what you're trying to do?";

  return {
    done:     false,
    question: safeQuestion,
    history:  nextHistory,
    usage:    response.usage,
  };
};

/**
 * buildFallbackContext — used when the interviewer's JSON response fails to
 * parse. Doesn't depend on the model's output at all — reconstructs a usable
 * structured_context directly from what the user actually typed across the
 * conversation, verbatim. Always succeeds, never throws.
 */
const buildFallbackContext = (history) => {
  const userMessages = history
    .filter(m => m.role === "user")
    .map(m => m.content)
    .join("\n\n");
  const lastUser = [...history].reverse().find(m => m.role === "user");

  return {
    goal:             lastUser?.content?.slice(0, 200) ?? "complete the task",
    existing_context: userMessages,
    already_tried:    null,
    expected_output:  null,
    constraints:      null,
    domain:           null,
    raw_intent:       history[0]?.content ?? "",
    complexity:       "medium",
  };
};

export const forceExtractContext = async (history) => {
  // Build context directly from conversation history
  // Grab all user messages and concatenate — preserves full pasted content
  const userMessages = history
    .filter(m => m.role === "user")
    .map(m => m.content)
    .join("\n\n");

  const response = await client.chat.completions.create({
    model:    "llama-3.3-70b-versatile",
    messages: [
      { role: "system", content: INTERVIEWER_SYSTEM_PROMPT },
      ...history,
      {
        role:    "user",
        content: "That's all the context I have. Build the structured_context JSON now. Store all pasted content verbatim in existing_context. Set unknown fields to null.",
      },
    ],
    max_tokens: 2000,
  });

  const reply = response.choices[0].message.content.trim();

  const jsonMatch = reply.match(/\{[\s\S]*"structured_context"[\s\S]*\}/);
  if (jsonMatch) {
    try {
      const parsed = JSON.parse(jsonMatch[0]);
      return parsed.structured_context ?? parsed;
    } catch (_) {}
  }

  // Fallback: build context directly from what user said
  const lastUser = [...history].reverse().find(m => m.role === "user");
  return {
    goal:             lastUser?.content ?? "complete the task",
    existing_context: userMessages,
    already_tried:    null,
    expected_output:  null,
    constraints:      null,
    domain:           null,
    raw_intent:       history[0]?.content ?? "",
    complexity:       "medium",
  };
};